---
title: "Task 2 - Cake Recipes"
output: html_notebook
---

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(skimr)
library(stringr)
library(here)
```

```{r}
here()
cakes <- read_csv(here("data/clean_data/cakes_clean.csv"))
```

1.2.2 Analysis questions
1. Which cake has the most cocoa in it?

```{r}
most_cocoa_cake <- cakes %>% 
  filter(ingredient == "Cocoa") %>% 
  slice_max(quantity)
```

2. For sponge cake, how many cups of ingredients are used in total?
```{r}
sponge_cake_test <- cakes %>% 
  filter(cake == "Sponge",
         measure == "cup") %>% 
  summarise(total_quantity = sum(quantity))
```

3. How many ingredients are measured in teaspoons?

```{r}
n_in_teaspoons <- cakes %>% 
  filter(measure == "teaspoon") %>% 
  distinct(ingredient) %>% 
  summarise(n_ingredients_teaspoon = n())
```

4. Which cake has the most unique ingredients?

```{r}
most_unique_ingred <- cakes %>% 
  group_by(cake) %>% 
  summarise(total_no_ingred = n()) %>% 
  arrange(desc(total_no_ingred)) %>% 
  head(2)
```

5. Which ingredients are used only once?

```{r}
ingedients_once <- cakes %>% 
  group_by(ingredient) %>% 
  mutate(times_used = n()) %>% 
  filter(times_used == 1) %>% 
  select(ingredient, times_used)
```



