---
title: "Dirty Data Project - Task 2"
output: html_notebook
---

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(skimr)
library(stringr)
```

# Read in the data

```{r}
cake_recipes <- read_csv("data/raw_data/cake-ingredients-1961.csv")
cake_codes <- read_csv("data/raw_data/cake_ingredient_code.csv")
```
# view the data

```{r}
dim(cake_recipes)
skim(cake_recipes)
summary(cake_recipes)
```
# Tidy in to long format

```{r}
cake_recipes_long <- cake_recipes %>% 
  pivot_longer(cols = ("AE":"ZH"),
               names_to = "code",
               values_to = "quantity")
```

# Drop the NA values as we don't need info on ingredients not included

```{r}
cake_recipes_dropna <- cake_recipes_long %>% 
  drop_na(quantity)
```

# Join with the cake_codes table to get full ingredient name
```{r}
cake_recipes_full <- cake_recipes_dropna %>% 
  left_join(cake_codes, by = "code")

```
# Clean the headers

```{r}
cake_recipes_full_clean <- cake_recipes_full %>% 
  clean_names()

```

# Remove the "code" leaving only the information we want

```{r}
cake_recipe_clean <- cake_recipes_full_clean %>% 
  select(cake, ingredient, measure, quantity)
cake_recipe_clean
```

# change the sour cream NA values to cup
```{r}
cake_recipe_clean_sour <- cake_recipe_clean %>% 
  mutate(measure = coalesce(measure, "cup"))

```

# remove the "cup" from "Sour cream cup"

```{r}
cake_recipe_clean_cup_remove <- cake_recipe_clean_sour %>% 
  mutate(ingredient = str_remove(ingredient, " cup"))
```

# data is now fully clean

```{r}
cakes_clean <- cake_recipe_clean_cup_remove
```

```{r}
cakes_clean %>% 
  distinct(measure)
```
```{r}
most_cocoa_cake <- cakes_clean %>% 
  filter(ingredient == "Cocoa") %>% 
  slice_max(quantity)
```

```{r}
sponge_cake_test <- cakes_clean %>% 
  filter(cake == "Sponge",
         measure == "cup") %>% 
  summarise(total_quantity = sum(quantity))
```

```{r}
n_in_teaspoons <- cakes_clean %>% 
  filter(measure == "teaspoon") %>% 
  distinct(ingredient) %>% 
  summarise(n_ingredients_teaspoon = n())
```

```{r}
most_unique_ingred <- cakes_clean %>% 
  group_by(cake) %>% 
  summarise(total_no_ingred = n()) %>% 
  arrange(desc(total_no_ingred)) %>% 
  head(2)
```

```{r}
ingedients_once <- cakes_clean %>% 
  group_by(ingredient) %>% 
  mutate(times_used = n()) %>% 
  filter(times_used == 1) %>% 
  select(ingredient, times_used)
```


